"""GlyphWiki PUA ligature pipeline (in-tree KAGE renderer)."""

from __future__ import annotations

from .engine import REFERENCE_STROKE, Kage, make_engine, mirror_stroke_data, render_stroke_data
from .mapping import (
    D4_MODES,
    DEFAULT_VS_MARKER,
    MirrorVS,
    VS01,
    VS02,
    VS03,
    VS04,
    VS05,
    VS06,
    VS07,
    VS08,
    assign_ligatures,
    filter_alias_entries,
    filter_duplicate_stroke_entries,
    filter_empty_stroke_entries,
    filter_excluded_entries,
    filter_related_entries,
    is_allowed_related,
    is_empty_stroke_data,
    is_excluded_glyph,
    is_non_mincho_stroke_data,
    ligature_capacity,
    make_vs,
    mirror_sequence,
    mirror_vs,
    pack_capacity,
    related_allow_ranges,
)

__all__ = [
    "D4_MODES",
    "DEFAULT_VS_MARKER",
    "Kage",
    "MirrorVS",
    "REFERENCE_STROKE",
    "VS01",
    "VS02",
    "VS03",
    "VS04",
    "VS05",
    "VS06",
    "VS07",
    "VS08",
    "assign_ligatures",
    "filter_alias_entries",
    "filter_duplicate_stroke_entries",
    "filter_empty_stroke_entries",
    "filter_excluded_entries",
    "filter_related_entries",
    "is_allowed_related",
    "is_empty_stroke_data",
    "is_excluded_glyph",
    "is_non_mincho_stroke_data",
    "ligature_capacity",
    "make_engine",
    "make_vs",
    "mirror_sequence",
    "mirror_stroke_data",
    "mirror_vs",
    "pack_capacity",
    "related_allow_ranges",
    "render_stroke_data",
]
